### ISSUE TITLE
Now do it in standard C and report back to us

### ISSUE THREAD

**Issue by DBJDBJ** [Tednesday/cpp-contiguous-circular-queue#1]
# 😛

**Comment by Tednesday** [comment]
Sure

**Comment by Tednesday** [comment]
https://github.com/Tednesday/cpp-contiguous-circular-queue/blob/a8e8e76df4acf9e3801944f97b72335e0d5bb8cc/queue_c.h#L1

**Comment by DBJDBJ** [comment]
No wonder modern C++ practitioners are switching to the (strong) state of denial upon seeing this.

Well done. Thank you.

**Comment by Tednesday** [comment]
Not quite sure I understand what you are saying.

**Comment by DBJDBJ** [comment]
When a person who considers herself modern C++ expert, sees this kind of C code solving rather effortlessly the same requirement as presented in parallel in C++code with issues pointed out, that same person has a emotional reaction called state of denial. That is my experience.

Well done. Thank you.

ps: In this kind of situations some C++ experts  might produce C++20 meta programing counter example  in order to prove two points: 1. The author does not know how to write C++ and 2. C++ is obviously faster than C. That code is usually more than one thousand lines long single header, of course 😃. That is also my experience.

**Comment by Tednesday** [comment]
I see yes I understand.
